16/03/2020 21:33:40 [INFO] werkzeug[_log] [_internal.py 113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
16/03/2020 21:33:40 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:33:43 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:33:43 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:34:53 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 21:34:53 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:34:53] "[37mGET / HTTP/1.1[0m" 200 -]
16/03/2020 21:42:34 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/app.py', reloading]
16/03/2020 21:42:36 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:42:43 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:42:43 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:42:47 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/app.py', reloading]
16/03/2020 21:42:47 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:42:54 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:42:54 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:42:56 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/app.py', reloading]
16/03/2020 21:42:56 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:43:02 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:43:02 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:43:07 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/app.py', reloading]
16/03/2020 21:43:08 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:43:13 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:43:13 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:43:21 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 21:43:21 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 21:43:22 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:43:22] "[37mGET / HTTP/1.1[0m" 200 -]
16/03/2020 21:45:26 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 21:45:27 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:56:54 [INFO] werkzeug[_log] [_internal.py 113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
16/03/2020 21:56:54 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:56:57 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:56:57 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:57:00 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 21:57:00 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 21:57:00 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:00] "[35m[1mGET / HTTP/1.1[0m" 500 -]
16/03/2020 21:57:02 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:02] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -]
16/03/2020 21:57:02 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:02] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -]
16/03/2020 21:57:02 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:02] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -]
16/03/2020 21:57:03 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:03] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -]
16/03/2020 21:57:17 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 21:57:17 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 21:57:18 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:18] "[35m[1mGET / HTTP/1.1[0m" 500 -]
16/03/2020 21:57:19 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:19] "[37mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 200 -]
16/03/2020 21:57:19 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:19] "[37mGET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1[0m" 200 -]
16/03/2020 21:57:19 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:19] "[37mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 200 -]
16/03/2020 21:57:21 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:57:21] "[37mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 200 -]
16/03/2020 21:57:56 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 21:57:57 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:58:04 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:58:04 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:58:06 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 21:58:14 [INFO] werkzeug[_log] [_internal.py 113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
16/03/2020 21:58:14 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 21:58:18 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 21:58:18 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 21:58:18 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 21:58:18 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 21:58:19 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 21:58:19] "[37mGET / HTTP/1.1[0m" 200 -]
16/03/2020 22:00:06 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 22:00:07 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 22:00:13 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 22:00:13 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 22:00:24 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 22:00:25 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 22:00:31 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 22:00:31 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 22:00:38 [INFO] werkzeug[_log] [_internal.py 113  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)]
16/03/2020 22:00:38 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
16/03/2020 22:00:42 [WARNING] werkzeug[_log] [_internal.py 113  * Debugger is active!]
16/03/2020 22:00:42 [INFO] werkzeug[_log] [_internal.py 113  * Debugger PIN: 895-507-942]
16/03/2020 22:00:42 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 22:00:42 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 22:00:43 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 22:00:43] "[37mGET / HTTP/1.1[0m" 200 -]
16/03/2020 22:00:52 [INFO] root[index] [app.py 29 Rota acessada com sucesso]
16/03/2020 22:00:52 [WARNING] root[index] [app.py 30 log de warning]
16/03/2020 22:00:52 [INFO] werkzeug[_log] [_internal.py 113 127.0.0.1 - - [16/Mar/2020 22:00:52] "[37mGET / HTTP/1.1[0m" 200 -]
16/03/2020 22:02:08 [INFO] werkzeug[_log] [_internal.py 113  * Detected change in '/home/developer/521python/Projeto/config.py', reloading]
16/03/2020 22:02:09 [INFO] werkzeug[_log] [_internal.py 113  * Restarting with stat]
[16/03/2020 22:02:17] [INFO] werkzeug[_log] [_internal.py 113]  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[16/03/2020 22:02:17] [INFO] werkzeug[_log] [_internal.py 113]  * Restarting with stat
[16/03/2020 22:02:21] [WARNING] werkzeug[_log] [_internal.py 113]  * Debugger is active!
[16/03/2020 22:02:21] [INFO] werkzeug[_log] [_internal.py 113]  * Debugger PIN: 895-507-942
[16/03/2020 22:02:24] [INFO] root[index] [app.py 29] Rota acessada com sucesso
[16/03/2020 22:02:24] [WARNING] root[index] [app.py 30] log de warning
[16/03/2020 22:02:24] [covid] root[index] [app.py 31] Cheguei
[16/03/2020 22:02:24] [INFO] werkzeug[_log] [_internal.py 113] 127.0.0.1 - - [16/Mar/2020 22:02:24] "[37mGET / HTTP/1.1[0m" 200 -
[16/03/2020 22:02:50] [INFO] werkzeug[_log] [_internal.py 113]  * Detected change in '/home/developer/521python/Projeto/config.py', reloading
[16/03/2020 22:02:51] [INFO] werkzeug[_log] [_internal.py 113]  * Restarting with stat
[16/03/2020 22:02:57] [WARNING] werkzeug[_log] [_internal.py 113]  * Debugger is active!
[16/03/2020 22:02:57] [INFO] werkzeug[_log] [_internal.py 113]  * Debugger PIN: 895-507-942
